### ISSUE TITLE
Player Section Roadmap

### ISSUE THREAD

**Issue by DrPitLazarus** [DrPitLazarus/devinity-dashboard#1]
### Player

- [x] Flood
  - [x] Summary
  - [x] Achievements
  - [x] Fav. Props
  - [x] Fav. Weapons
  - [x] Owned Weapons
- [x] Battle Royale
  - [x] Summary
  - [x] Achievements
  - [x] Deaths
  - [x] Items
  - [x] Kills
- [ ] Bans
  - [x] Steam VAC and Game bans
  - [x] Devinity active ban
  - [ ] Devinity infractions
- [x] Search player from a list
  - [x] Staff
  - [x] Connected and recent Flood players
  - [x] Connected and recent BR players
- [ ] Additional links (infractions, activity log, server log...)
