### ISSUE TITLE
Infractions Section Roadmap

### ISSUE THREAD

**Issue by DrPitLazarus** [DrPitLazarus/devinity-dashboard#5]
### Infractions

- [ ] Active Bans
  - [x] Show x recent bans.
  - [ ] Search bar to see ban status by Steam ID. Probably a detail view too.
- [ ] History
  - [x] Show x recent infractions.
  - [x] Search and filtering results.
  - [ ] Detail view.
